services:
  - type: web
    name: bloodsync-backend
    env: docker
    plan: free
    buildCommand: cd backened/backened/demo && ./gradlew build
    startCommand: java -jar backened/backened/demo/build/libs/app.jar
    healthCheckPath: /api/actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://bloodsync-frontend.vercel.app
    autoDeploy: true
