"""empty message

Revision ID: 47af1777b7de
Revises: 
Create Date: 2025-03-09 16:00:22.877510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47af1777b7de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_donor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userName', sa.String(length=50), nullable=True),
    sa.Column('firstName', sa.String(length=50), nullable=True),
    sa.Column('lastName', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('imageURL', sa.String(length=255), nullable=True),
    sa.Column('bloodDonorType', sa.String(length=20), nullable=True),
    sa.Column('additionalInfo', sa.String(length=255), nullable=True),
    sa.Column('location_pincode', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('blood_receiver',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userName', sa.String(length=50), nullable=True),
    sa.Column('firstName', sa.String(length=50), nullable=True),
    sa.Column('lastName', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('imageURL', sa.String(length=255), nullable=True),
    sa.Column('bloodRecieverType', sa.String(length=20), nullable=True),
    sa.Column('additionalInfo', sa.String(length=255), nullable=True),
    sa.Column('location_pincode', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('blood_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullName', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=35), nullable=False),
    sa.Column('phonenumber', sa.String(length=15), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('blood_type', sa.String(length=5), nullable=False),
    sa.Column('units_needed', sa.Integer(), nullable=False),
    sa.Column('date_issued', sa.DateTime(), nullable=False),
    sa.Column('urgency_level', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phonenumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blood_request')
    op.drop_table('blood_receiver')
    op.drop_table('blood_donor')
    op.drop_table('admin_account')
    # ### end Alembic commands ###
